config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'

  post "favorites/:question_id/create" => "favorites#create"
  post "favorites/:question_id/destroy" => "favorites#destroy"
  
  resources :questions do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 0, name: '--' },
    { id: 1, name: '健康・病気・病院' },
    { id: 2, name: 'コスメ・美容・整形' },
    { id: 3, name: 'ファッション' },
    { id: 4, name: '家族・友達' },
    { id: 5, name: '恋愛・結婚' },
    { id: 6, name: 'お仕事' },
    { id: 7, name: 'パパ活' },
    { id: 8, name: 'R-18' }
  ]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :question

  validates :text, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :category

  belongs_to :user
  has_many :comments
  has_many :favorites
  has_many :users, through: :favorites
  has_one_attached :image

  with_options presence: true do
    validates :category_id, numericality: { other_than: 0 }
    validates :title
    validates :text
    validates :image, presence: true, unless: :was_attached?
  end

  def was_attached?
    image.attached?
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :questions
  has_many :comments
  has_many :favorites
  has_many :posts, through: :favorites

  enum gender: { yet: 0, already: 1 }

  with_options presence: true do
    validates :nickname
    validates :first_name
    validates :last_name
    validates :birthday
    validates :gender
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV['BASIC_AUTH_USER'] && password == ENV['BASIC_AUTH_PASSWORD']
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname, :first_name, :last_name, :birthday, :gender])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :authenticate_user!
before_action :move_to_question, only: [:create, :destroy]

  def create
    @comment = current_user.comments.new(comment_params)
    if @comment.save
      redirect_to @question
    else
      render 'questions/show'  #仮の記述
    end
  end

  def destroy
    comment = Comment.find_by(id: params[:id], question_id: params[:question_id])
    comment.destroy
    redirect_to @question
  end

  private

  def comment_params
    params.require(:comment).permit(:text).merge(user_id: current_user.id, question_id: params[:question_id])
  end

  def move_to_question
    @question = Question.find(params[:question_id])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = Favorite.new(user_id: current_user.id, question_id: params[:question_id])
    @favorite.save
    redirect_to("/questions/#{params[:question_id]}")
  end
  
  def destroy
    @favorite = Favorite.find_by(user_id: current_user.id, question_id: params[:question_id])
    @favorite.destroy
    redirect_to("/questions/#{params[:question_id]}")
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :specified_question, only: [:show, :edit, :update, :destroy]
  before_action :specified_user, only: [:edit, :destroy]

  def index
    @questions = Question.order('created_at DESC')
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @question.comments.includes(:user)
    @favorites_count = Favorite.where(question_id: @question.id).count
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to action: :show
    else
      render :edit
    end
  end

  def destroy
    if @question.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def question_params
    params.require(:question).permit(:category_id, :title, :text, :image).merge(user_id: current_user.id)
  end

  def specified_question
    @question = Question.find(params[:id])
  end

  def specified_user
    redirect_to root_path unless @question.user.id == current_user.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def simple_time(time)
    time.strftime("%Y-%m-%d [%H:%M] ")
  end 
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Managender</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="question-list">
<%= link_to question.title, question_path(question.id)%>
  <div class="posted-by">
  ユーザー名さん
</div>

app/views/questions/edit.html.erb
<%= render "shared/header" %>

<h1>お悩みボックス</h1>

<h3>お悩みボックスでは、困っていることや解決したいことについて、悩める乙女同士で一緒にシェアしていきましょう！</h3>


<div class="question-main">
  <h2 class="question-title">悩める内容を教えてください</h2>
  <%= form_with model: @question, url: question_path, method: :patch, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <%# 質問カテゴリー %>
  <div class="question-category">
    質問カテゴリー
    <span class="indispensable">必須</span>
  </div>
  <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"question-category"}) %>
  
  <%# 質問タイトル %>
  <div class="question-title">
    質問タイトル
    <span class="indispensable">必須</span>
  </div>
  <%= f.text_field :title, class:"title-input", id:"title_id", placeholder:"質問タイトルを入力（必須 60文字まで)", maxlength:"60" %>

  <%# 質問内容 %>
  <div class="question-text">
    質問内容
    <span class="indispensable">必須</span>
  </div>
  <%= f.text_area :text, class:"text-text", id:"text_id", placeholder:"質問内容" %>

  <%# 画像添付 %>
  <div class="image-field">
    <%= f.label :image, "質問に関する画像" %><br />
    <%= f.file_field :image %>
  </div>

  <%# 送信ボタン %>
  <div class="question-submit-btn">
    <%= f.submit "質問内容を更新する", class:"question-submit-btn" %>
  </div>

  <% end %>
</div>

app/views/questions/index.html.erb
<%= render "shared/header" %>

<div class='main'>

  <%# 画面上部に「Managenderへようこそ」 %>
  <h1>Managender</h1>
  <h3>悩める性転換系女子のために</h3>
  <h3>美と愛を管理するアプリ</h3>

  <% if user_signed_in? %>
  <div class='post-btn'>
    <%= link_to '質問する', new_question_path %>
  </div>
  <% end %>

  <%# 質問一覧 %>
  <div class='question-contents'>
    <h2 class='title'>お悩み一覧</h2>
    <ul class='unset'>  
    <%# 部分テンプレートで質問投稿一覧を表示する %>
    <%= render partial: 'question', collection: @questions %>
  </div>

</div>

app/views/questions/new.html.erb
<%= render "shared/header" %>

<h1>お悩みボックス</h1>

<h3>お悩みボックスでは、困っていることや解決したいことについて、悩める乙女同士で一緒にシェアしていきましょう！</h3>


<div class="question-main">
  <h2 class="question-title">悩める内容を教えてください</h2>
  <%= form_with model: @question, url: questions_path, method: :post, local: true do |f| %>

  <%= render 'shared/error_messages', model: f.object %>

  <%# 質問カテゴリー %>
  <div class="question-category">
    質問カテゴリー
    <span class="indispensable">必須</span>
  </div>
  <%= f.collection_select(:category_id, Category.all, :id, :name, {}, {class:"select-box", id:"question-category"}) %>
  
  <%# 質問タイトル %>
  <div class="question-title">
    質問タイトル
    <span class="indispensable">必須</span>
  </div>
  <%= f.text_field :title, class:"title-input", id:"title_id", placeholder:"質問タイトルを入力（必須 60文字まで)", maxlength:"60" %>

  <%# 質問内容 %>
  <div class="question-text">
    質問内容
    <span class="indispensable">必須</span>
  </div>
  <%= f.text_area :text, class:"text-text", id:"text_id", placeholder:"質問内容", rows: "5", cols: "59" %>

  <%# 画像添付 %>
  <div class="image-field">
    <%= f.label :image, "質問に関する画像" %><br />
    <%= f.file_field :image %>
  </div>

  <%# 送信ボタン %>
  <div class="question-submit-btn">
    <%= f.submit "質問を完了する", class:"question-submit-btn" %>
  </div>

  <% end %>
</div>

app/views/questions/show.html.erb
<%= render "shared/header" %>

<div class="user-nickname">
<%= "#{@question.user.nickname}さんによる投稿" %>
</div>

  <% if user_signed_in? && current_user.id == @question.user.id %>
    <%= link_to '編集する', edit_question_path(@question.id), method: :get %>
    <%= link_to '削除する', question_path(@question.id), method: :delete %>
  <% end %>

<div>
  質問タイトル
</div>
<div>
  <%= @question.title %>
</div>

<div>
  質問カテゴリー
</div>
<div>
  <%= @question.category.name %>
</div>

<div>
  質問内容
</div>
<div>
  <%= @question.text%>
</div>

<div>
  画像
</div>
<%= image_tag @question.image.variant(resize: '200x200'), class: 'question-image' if @question.image.attached? %>

<%= render 'shared/error_messages', model: @comment %>

<% if user_signed_in? %>

  <% if Favorite.find_by(user_id: current_user.id, question_id: @question.id) %>
    <%=link_to("いいね[★]", "/favorites/#{@question.id}/destroy", {method: "post"})%>
  <% else %>
    <%= link_to("いいね[☆]", "/favorites/#{@question.id}/create", {method: "post"}) %>
  <% end %>
  <%= @favorites_count %>

  <%= form_with(model: [@question, @comment], local: true) do |form| %>
    <%= form.text_area :text, placeholder: "コメントする", rows: "5", cols: "59" %>
      <div>
        <%= form.submit "投稿" %>
      </div>
  <% end %>

  <% if @comments %>
    <% @comments.each do |comment| %>
      <p>
        <strong><%= link_to comment.user.nickname, "/users/#{comment.user_id}" %>：</strong>
        <%= comment.text %>
        <%= simple_time(comment.created_at) %>

        <% if current_user.id == comment.user_id %>
          <%= link_to '削除', question_comment_path(comment.question.id, comment.id), method: :delete %>
        <% end %>
      </p>
    <% end %>
  <% end %>
<% end %>

<div class="go-back-homepage">
<%=link_to "ホームへ戻る", root_path %>
</div>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_header.html.erb
<header class='top-header'>
  <div class='lists-left'>
  </div>

  <ul class='lists-right'>
    <% if user_signed_in? %>
    <li><%= link_to "#{current_user.nickname}さん", "#", class: "user-nickname" %></li>
    <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
    <% else %>
    <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
    <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
    <% end %>
  </ul>
</header>